language: android
sudo: required
jdk:
  - oraclejdk8

env:
 global:
 - ANDROID_API=25
 - EMULATOR_API=22
 - ANDROID_BUILD_TOOLS=25.0.2

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra
    - addon
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API
    - sys-img-armeabi-v7a-android-$EMULATOR_API

before_install:
    - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace --info


after_failure:
    - cat /home/travis/build/ethmobile/ethdroid/ethdroid/build/reports/lint-results.html
    - cat /home/travis/build/ethmobile/ethdroid/ethdroid/build/reports/androidTests/connected/index.html

before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
  -$HOME/.gradle/caches/
  -$HOME/.gradle/wrapper/
